// Generated by https://quicktype.io

import { Color } from "./models/color.interface";

export interface Pagination {
    totalPages: number;
    totalCount: number;
    pageSize: number;
    pageNumber: number;
    prev: StatusPage;
    next: StatusPage;
    data: any[];
}

export interface StatusPage {
    status: string;
    pageNumber: number;
}

export interface PaginateParameters {
    page: number;
    page_size: number;
    urlPrefix: string;
    params?: {};

}
