// Generated by https://quicktype.io

export interface Category {
    id:            number;
    name:          string;
    subCategories: any[];
    createdAt:     null;
    updatedAt:     null;
    deletedAt:     null;
}
