// Generated by https://quicktype.io

export interface Color {
    id:               number;
    code:             string;
    name:             string;
    supplierCode:     null;
    description:      string;
    image:            string;
    brandId:          number;
    materialTypeId:   number;
    brand:            Brand;
    materialType:     MaterialType;
    subTypeMaterials: SubTypeMaterial[];
    createdAt:        null;
    updatedAt:        null;
    deletedAt:        null;
    forDoors:         boolean;      
    forStructure:     boolean;
}

export interface Brand {
    id:                     number;
    name:                   string;
    createdAt:              null;
    updateAt:               null;
    deletedAt:              null;
    drawerSlidesComponents: any[];
    drawerSlides:           any[];
    hinges:                 any[];
    hingeComponents:        any[];
    colors:                 null[];
}

export interface MaterialType {
    id:               number;
    name:             string;
    hasBarniz:        null;
    colors:           null[];
    subTypeMaterials: any[];
    createdAt:        null;
    updatedAt:        null;
    deletedAt:        null;
}

export interface SubTypeMaterial {
    id:                 number;
    name:               string;
    createdAt:          null;
    updatedAt:          null;
    deletedAt:          null;
    colors:             null[];
    finishes:           any[];
    materialTypes:      any[];
    internalAccesories: any[];
}
