// Generated by https://quicktype.io

export interface DrawerSlide {
    id:                number;
    code:              string;
    name:              string;
    price:             number;
    cost:              number;
    increaseFactor: null;
    description:       null;
    createdAt:         null;
    updateAt:          null;
    deletedAt:         null;
    brandId:           number;
    brand:             null;
    drawerSlideTypeId: number;
    drawerSlideType:   null;
    components:        any[];
}
