// Generated by https://quicktype.io

import { Brand } from "./color.interface";
import { HingeComponent } from "./hingeComponent.interface";

export interface Hinge {
    id:          number;
    code:        Code;
    name:        string;
    description: null | string;
    observation: null;
    createdAt:   null;
    updateAt:    null;
    deletedAt:   null;
    brandId:     null;
    brand:       Brand;
    angleId:     number;
    angle:       Angle;
    increaseFactor: null;
    hingeTypeId: number;
    hingeType:   null;
    hingeHingeComponents:  HingeHingeComponent[];
}
export interface HingeHingeComponent {
    id?:          number;
    hingeId?:     number;
    componentId?: number;
    quantity:    number;
    hinge?:       null;
    component:   HingeComponent;
}

export interface Angle {
    id:        number;
    name:      string;
    value?:    number;
    createdAt: null;
    updateAt:  null;
    deletedAt: null;
    hinges:    null[];
}

export enum Code {
    Bis100 = "BIS-100",
    Bis180 = "BIS-180",
    Bis45 = "BIS-45",
    BisNeg = "BIS-NEG",
}

