// Generated by https://quicktype.io

export interface Line {
    id:         number;
    name:       string;
    createdAt:  null;
    updatedAt:  null;
    deletedAt:  null;
    doorModels: any[];
}
