// Generated by https://quicktype.io

export interface Materialtype {
    id:               number;
    name:             string;
    hasBarniz:        string;
    createdAt:        null;
    updatedAt:        null;
    deletedAt:        null;
    subTypeMaterials: any[];
}
