// Generated by https://quicktype.io

export interface Material {
    id:                number;
    name:              string;
    description:       string;
    weightPerM2:       string;
    subGroupId:        number;
    subTypeMaterialId: number;
    materialTypeId:    number;
    createdAt:         null;
    updatedAt:         null;
    deletedAt:         null;
    materialType:      null;
    subTypeMaterial:   null;
    glasses:           any[];
}
