// Generated by https://quicktype.io

export interface SubCategory {
    id:               number;
    name:             string;
    category:         null;
    categoryId:       number;
    subSubCategories: any[];
    createdAt:        null;
    updatedAt:        null;
    deletedAt:        null;
}

export interface Category {
    id:            number;
    name:          string;
    subCategories: any[];
    createdAt:     null;
    updatedAt:     null;
    deletedAt:     null;
}

export interface Brand {
    id:                     number;
    name:                   string;
    subSubCategories:       any[];
    drawerSlidesComponents: any[];
    drawerSlides:           any[];
    hinges:                 any[];
    hingeComponents:        null[];
    colors:                 any[];
    createdAt:              null;
    updateAt:               null;
    deletedAt:              null;
}