// Generated by https://quicktype.io

export interface SubTypeMaterial {
    id:                 number;
    name:               string;
    createdAt:          null;
    updatedAt:          null;
    deletedAt:          null;
    colors:             null[];
    finishes:           any[];
    materialTypes:      any[];
    internalAccesories: any[];
}
